[parity]
chain = "foundation"

[network]
min_peers = 50
max_peers = 100

[footprint]
db_compaction = "ssd"
cache_size = 4096

[rpc]
interface = "0.0.0.0"
hosts = ["all"]

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
